language: ruby
sudo: false
before_install:
  - bundle update
rvm:
  - 2.2.7
  - 2.3.4
  - ruby-head
env:
  - "RAILS_VERSION=5.1.3"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
